# Generated by Django 5.2 on 2026-03-26 04:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio Neto'), ('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=20, verbose_name='Tipo')),
                ('acepta_movimientos', models.BooleanField(default=True, verbose_name='Acepta movimientos')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='contabilidad.cuentacontable', verbose_name='Cuenta padre')),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Cuentas contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20, verbose_name='Estado')),
                ('ejercicio_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejercicios_siguientes', to='contabilidad.ejercicio', verbose_name='Ejercicio anterior')),
            ],
            options={
                'verbose_name': 'Ejercicio contable',
                'verbose_name_plural': 'Ejercicios contables',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('venta', 'Venta'), ('compra', 'Compra'), ('tesoreria', 'Tesorería'), ('manufactura', 'Manufactura')], default='manual', max_length=20, verbose_name='Origen')),
                ('origen_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID origen')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='contabilidad.ejercicio', verbose_name='Ejercicio')),
            ],
            options={
                'verbose_name': 'Asiento contable',
                'verbose_name_plural': 'Asientos contables',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='LineaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Debe')),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Haber')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.asiento', verbose_name='Asiento')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='contabilidad.cuentacontable', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Línea de asiento',
                'verbose_name_plural': 'Líneas de asiento',
            },
        ),
    ]
