# Generated by Django 5.2 on 2026-03-26 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='ejercicio_consolidado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejercicios_desconsolidar', to='contabilidad.ejercicio', verbose_name='Ejercicio consolidado anterior'),
        ),
    ]
