# Generated by Django 5.2 on 2026-04-04 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alicuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje')),
                ('jurisdiccion', models.CharField(blank=True, default='Nacional', max_length=100, verbose_name='Jurisdicción')),
                ('fecha_desde', models.DateField(verbose_name='Vigente desde')),
                ('fecha_hasta', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('por_defecto', models.BooleanField(default=False, verbose_name='Por defecto')),
            ],
            options={
                'verbose_name': 'Alícuota',
                'verbose_name_plural': 'Alícuotas',
                'ordering': ['-fecha_desde'],
            },
        ),
        migrations.CreateModel(
            name='TipoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('iva', 'IVA'), ('iibb', 'IIBB'), ('retencion', 'Retención'), ('percepcion', 'Percepción'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cuenta_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_impuesto', to='contabilidad.cuentacontable', verbose_name='Cuenta contable')),
            ],
            options={
                'verbose_name': 'Tipo de impuesto',
                'verbose_name_plural': 'Tipos de impuesto',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('jurisdiccion', models.CharField(choices=[('nacional', 'Nacional'), ('provincial', 'Provincial'), ('municipal', 'Municipal')], default='nacional', max_length=20, verbose_name='Jurisdicción')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('aplica_compras', models.BooleanField(default=True, verbose_name='Aplica a compras')),
                ('aplica_ventas', models.BooleanField(default=True, verbose_name='Aplica a ventas')),
                ('requiere_constancia', models.BooleanField(default=False, verbose_name='Requiere constancia')),
                ('alicuota_por_defecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.alicuota', verbose_name='Alícuota por defecto')),
                ('cuenta_contable_debe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Cuenta debe')),
                ('cuenta_contable_haber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Cuenta haber')),
                ('tipo_impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='contabilidad.tipoimpuesto', verbose_name='Tipo de impuesto')),
            ],
            options={
                'verbose_name': 'Configuración de impuesto',
                'verbose_name_plural': 'Configuraciones de impuesto',
            },
        ),
        migrations.AddField(
            model_name='alicuota',
            name='tipo_impuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alicuotas', to='contabilidad.tipoimpuesto', verbose_name='Tipo de impuesto'),
        ),
    ]
