# Generated by Django 5.2 on 2026-03-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_ejercicio_ejercicio_consolidado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('venta', 'Venta'), ('compra', 'Compra'), ('tesoreria', 'Tesorería'), ('manufactura', 'Manufactura'), ('apertura', 'Apertura'), ('cierre', 'Cierre'), ('ajuste', 'Ajuste')], default='manual', max_length=20, verbose_name='Origen'),
        ),
    ]
