# Generated by Django 5.2 on 2026-04-03 22:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('caja', 'Caja'), ('banco', 'Banco'), ('digital', 'Billetera digital')], max_length=20, verbose_name='Tipo')),
                ('moneda', models.CharField(choices=[('ARS', 'Peso Argentino'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='ARS', max_length=3, verbose_name='Moneda')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo inicial')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_tesoreria', to='contabilidad.cuentacontable', verbose_name='Cuenta contable')),
            ],
            options={
                'verbose_name': 'Cuenta de tesorería',
                'verbose_name_plural': 'Cuentas de tesorería',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('anulado', 'Anulado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('tipo', models.CharField(choices=[('cobro', 'Cobro'), ('pago', 'Pago'), ('transferencia', 'Transferencia')], max_length=20, verbose_name='Tipo')),
                ('asiento_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_tesoreria', to='contabilidad.asiento', verbose_name='Asiento contable')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_tesoreria', to='contactos.contacto', verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Movimiento de tesorería',
                'verbose_name_plural': 'Movimientos de tesorería',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='LineaMovimientoTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Debe')),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Haber')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='tesoreria.cuentatesoreria', verbose_name='Cuenta de tesorería')),
                ('cuenta_contrapartida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Cuenta contrapartida')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='tesoreria.movimientotesoreria', verbose_name='Movimiento')),
            ],
            options={
                'verbose_name': 'Línea de movimiento',
                'verbose_name_plural': 'Líneas de movimiento',
            },
        ),
    ]
