# Generated by Django 5.2 on 2026-03-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientotesoreria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripción'),
        ),
    ]
