# Generated by Django 5.2 on 2026-04-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientotesoreria',
            name='tipo',
            field=models.CharField(choices=[('cobro', 'Cobro'), ('pago', 'Pago'), ('transferencia', 'Transferencia'), ('ajuste', 'Ajuste de saldo')], max_length=20, verbose_name='Tipo'),
        ),
    ]
