# Generated by Django 5.2 on 2026-04-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón social')),
                ('nombre_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nombre de fantasía')),
                ('cuil', models.CharField(max_length=13, verbose_name='CUIL/CUIT')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('web', models.URLField(blank=True, verbose_name='Sitio web')),
                ('condicion_iva', models.CharField(default='Responsable Inscripto', max_length=50, verbose_name='Condición frente al IVA')),
                ('numero_ingresos_brutos', models.CharField(blank=True, max_length=50, verbose_name='Número de Ingresos Brutos')),
                ('inicio_actividades', models.DateField(blank=True, null=True, verbose_name='Inicio de actividades')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/logos', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Datos de la empresa',
                'verbose_name_plural': 'Datos de la empresa',
            },
        ),
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('clave', models.CharField(max_length=50, unique=True, verbose_name='Clave')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripcion')),
                ('grupo', models.CharField(choices=[('empresa', 'Empresa'), ('contabilidad', 'Contabilidad'), ('ventas', 'Ventas'), ('compras', 'Compras'), ('tesoreria', 'Tesorería'), ('facturacion', 'Facturación'), ('integraciones', 'Integraciones')], default='empresa', max_length=20, verbose_name='Grupo')),
                ('editable', models.BooleanField(default=True, verbose_name='Editable')),
            ],
            options={
                'verbose_name': 'Parámetro del sistema',
                'verbose_name_plural': 'Parámetros del sistema',
                'ordering': ['grupo', 'clave'],
            },
        ),
    ]
