# Generated by Django 5.2 on 2026-04-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre o razón social')),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('cliente_proveedor', 'Cliente y Proveedor')], default='cliente', max_length=20, verbose_name='Tipo')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('cuil', models.CharField(blank=True, max_length=13, verbose_name='CUIL/CUIT')),
                ('condicion_iva', models.CharField(choices=[('responsable_inscripto', 'Responsable Inscripto'), ('monotributista', 'Monotributista'), ('exento', 'Exento'), ('consumidor_final', 'Consumidor Final'), ('no_responsable', 'No Responsable')], default='consumidor_final', max_length=30, verbose_name='Condición IVA')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('contacto_principal', models.CharField(blank=True, max_length=200, verbose_name='Contacto principal')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Límite de crédito')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['nombre'],
            },
        ),
    ]
